<?php

namespace NAO\CoreBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllObservationsUpdatedAfterDate($uneDate) {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder
            ->where('a.lastUpdate > :uneDate')
            ->setParameter('uneDate', $uneDate);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
