<?php

namespace NAO\CoreBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDateCreationEtObservateur($dateCreation, $observateur) {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.dateCreation = :dateCreation')
            ->setParameter('dateCreation', $dateCreation)
            ->andWhere('a.observateur = :observateur')
            ->setParameter('observateur',$observateur);
        return $qb->getQuery()->getResult();
    }

    public function getLastUpdate() {
        $qb = $this->createQueryBuilder('a')
            ->select('MAX(a.lastUpdate)');
        return $qb->getQuery()->getScalarResult();
    }
}
